app:
    name: Demo App
server:
    contextPath: /root
spring:
    datasource:
        name: demodb # Name of the datasource
        username: root
      #  password: 12345678
        password: H9L6O9E9al2i2s6E
      #  url: jdbc:mysql://localhost:3306/routes_db
        url: jdbc:mysql://google/routesdb2?cloudSqlInstance=ionic-161810:europe-west1:routesdb2
        driverClassName: com.mysql.jdbc.Driver
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        show-sql: true
        hibernate:
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
